export const COMMON_SET_ALERT = "COMMON_SET_ALERT";
export const COMMON_SET_SHOW_ALERT = "COMMON_SET_SHOW_ALERT";

export const COMMON_SET_INPUT_ERR = "COMMON_SET_INPUT_ERR";
export const COMMON_SET_SHOW_INPUT_ERR = "COMMON_SET_SHOW_INPUT_ERR";

export const COMMON_SET_REDIRECT = "COMMON_SET_REDIRECT";

export const COMMON_SET_POP_UP = "COMMON_SET_POP_UP";

export const COMMON_SET_LOADING = "COMMON_SET_LOADING";

export const COMMON_SET_BUTTON_LOADING = "COMMON_SET_BUTTON_LOADING";

export const COMMON_SET_DOCUMENT_TITLE = "COMMON_SET_DOCUMENT_TITLE";

export const COMMON_SET_SHOW_SIDE_MENU = "COMMON_SET_SHOW_SIDE_MENU";